### PR TITLE
max_misalignment, class SyncDetector

### PR DESCRIPTION
**Pull request by hhsprings**
For class SyncDetector, see the commit log and [my gist](https://gist.github.com/hhsprings/f79cd7c1ff6d50f6ae3db115b41bf09b#file-mk_stacked_movie_ffmpeg_script-py-L15).

### CODE REVIEW

**Comment by jeorgen** [comment]
Seems to work well!

I merged and have included three test files in tests/testfiles . Here's the result from the command line with three files:

```
./bin/python align_videos_by_sound_track.py \
tests/testfiles/full.mp4 \
tests/testfiles/3-secs-in.mp4  \
tests/testfiles/7-secs-in.mp4 
Result: The beginning of '/home/xxx/workspace/multimedia/align-videos-by-sound-python3/tests/testfiles/3-secs-in.mp4' needs to be cropped 3.0080 seconds for files to be in sync
Result: The beginning of '/home/xxx/workspace/multimedia/align-videos-by-sound-python3/tests/testfiles/7-secs-in.mp4' needs to be cropped 6.9973 seconds for files to be in sync
```

**Comment by jeorgen** [comment]
Hmm, except that it does the opposite of what it should…
It's `full.mp4` that needs to be cropped 7 seconds, and `3-secs-in.mp4` needs to be cropped 4 seconds…

**Comment by jeorgen** [comment]
Ok, I've fixed it I believe. Feel free to fix it nicer if you think it looks ugly.

**Comment by hhsprings** [comment]
> Hmm, except that it does the opposite of what it should…

My mistakes? Sorry, my purpose is to "pad" frames into "shorter video" rather than crop,
and I didn't care your __main__ section (, that is, "align" itself is what I want).

> if you think it looks ugly.

LGTM, at least for now :)

**Pull request merged**
