### PR TITLE
trim_post, pad_post

### PR DESCRIPTION
**Pull request by hhsprings**
With the request to align the start of media with audio, I think that it is often that you want to align the terminations. In fact, the script I am creating is also requiring padding at the end. Fortunately, dependency on `ffmpeg` is equivalent to dependency on `ffprobe`, you can get duration with `ffprobe`.

There are two pending issues.

* Whether the names "trim_post" and "pad_post" are indeed suitable?
* Maybe some people are not pleased if we call `ffprobe` unconditionally?

For the latter personally, I think that the cost of the `ffprobe` call is within the error range when handling realistic length movies, so there is no problem.

### CODE REVIEW

**Comment by jeorgen** [comment]
As long as the process of trimming/padding is automated, I do not think adding a bit of ffprobe time matters.

I wonder a bit about the use case for padding, is that so that you can line up the files as tracks in a video editor, and then cut to tracks as they start having video information? Or is it a multi-video presentation where you want a logo or something to show when a file does not have video for that time span?

My use case is mainly to have good audio from whatever microphones picks up best at the moment, for e.g interviews, presentations and theatre plays.

> Whether the names "trim_post" and "pad_post" are indeed suitable?

"end_trimming" and "end_padding" might be better words? I'm not sure I see a use case for "end_trimming" for me at least.

**Comment by hhsprings** [comment]
> I wonder a bit about the use case for padding, is that so that you can line up the files as tracks in a video editor, and then cut to tracks as they start having video information? Or is it a multi-video presentation where you want a logo or something to show when a file does not have video for that time span? 

Do you ever seen [my script](https://gist.github.com/hhsprings/f79cd7c1ff6d50f6ae3db115b41bf09b)? My purpose is (now) for multi-video presentation. For example, if there are shooting movies from four different angles of outdoor concerts, movies that are slow to start shooting can be pure black with no sound before the start (at least for me).

In a real concert movie, for example, I think one ignore the MC's greeting before starting, and others don't ignore. I want to keep that "MC greeting part", for example.

> My use case is mainly to have good audio from whatever microphones picks up best at the moment, for e.g interviews, presentations and theatre plays.

Yeah, of course I will use it for such a purpose. I do not think that which use case is more expensive. And also in your case, for example, if we want to overlay short "good angle shot" to base movie, we need padding.

> "end_trimming" and "end_padding" 

Please change those as you like. Because I am not native, I do not understand natural nuances.

**Comment by jeorgen** [comment]
A cool thing, that is outside the scope of this project, would be to automatically detect the best voice track at any given time. One could use signal to noise ratio and volume as criteria, but I'm not sure that is enough.

Once could also imagine identifying different people talking, and use that for switching sound tracks. However a cheap solution is to listen and switch manually, and then make the switch a bit earlier, due to to human reaction time.

Speaking about automation, one could e.g. process each voice track and decide its average volume, and then switch it in when the volume is consistently higher.

However it may be that one would need to be able to distinguish between voices and noises, and between different speakers, so it may become an artificial intelligence problem.

**Comment by hhsprings** [comment]
I am also interested in choosing a good voice track (and/or manipulating a bad voice track). In addition to the problem of noise, especially in the case of multi-angle images, the balance of the left and right channels may be felt as a problem. I do not have any idea on how to solve this problem for automation, but it may be possible to use not only audio but also video as a hint or something. Perhaps this is the domain of artificial intelligence.

**Pull request merged**
