### PR TITLE
Automate the performance improvement by adjusting the sampling rate, and adding sample application.

### PR DESCRIPTION
**Pull request by hhsprings**
Automate the performance improvement by adjusting the sampling rate.

### CODE REVIEW

**Comment by hhsprings** [comment]
I'd rearranged [this](https://gist.github.com/hhsprings/f79cd7c1ff6d50f6ae3db115b41bf09b), and added it as `simple_stack_videos.py`.

**Comment by jeorgen** [comment]
Cool with simple stack videos! Haven't tried it yet…

**Comment by jeorgen** [comment]
I guess you could also add all video and sound tracks synchronized in parallel into e.g. an .mkv (matroska) container, but not sure how many applications can handle such a multi video track file format.

https://en.wikipedia.org/wiki/Matroska

**Comment by hhsprings** [comment]
My main objective is currently the hard disk recorder that can (only) handle MPEG-4 AVC / H.264 / AAC-LC. In the first place I have never used the MKV / MKA container before. So, I am not interested in this for the moment.

But It is obvious that it will come in a variety of ways to be made possible by "align", and we think that we can make a variety of other interesting things. For example, you could do something like a switcher based on a timetable description in a simple text file.

**Pull request merged**
